### ISSUE TITLE
Certain configuration names cause CMake errors

### ISSUE THREAD

**Issue by TheSlowGrowth** [McMartin/FRUT#520]
I converted an existing application to a CMakeLists.txt file using `Jucer2Reproducer`. The original application contained exporter configurations with these names:

````
Debug (32bit)
Debug (64bit)
Release (32bit)
Release (64bit)
````

The generated CMakeLists.txt thus contains lines like these:
````
jucer_export_target_configuration(
   "Visual Studio 2017"
   NAME "Debug (32bit)"
   DEBUG_MODE ON
   # ...
)
````

When running cmake I get these errors:
````
CMake Error at FRUT/prefix/FRUT/cmake/Reproducer.cmake:4550 (target_link_libraries):
   Error evaluating generator expression:
      $<CONFIG:Debug (32bit)>
   Expression syntax not recognized.
````

If I remove the spaces and brackets so that the names are `Debug32bit`. `Release64bit`, etc. the error disappears. It appears to me that `${config}` in `$<CONFIG:${config}>` must be escaped in some way but according to the CMake documentation, only angular brackets, commas and semicolons have proper escape sequences.

I would love to learn how to escape these properly. If that's not possible it would be a good solution to convert the incompatible configuration names to something that is compatible when converting the project with `Jucer2Reproducer`. 

I would be happy to contribute a fix for this, but at this point I'm unsure which option to choose.

**Comment by McMartin** [comment]
I found out that since [its introduction in 2012](https://gitlab.kitware.com/cmake/cmake/commit/9d9f616792ee07a460af9f0a6dc036d81b852e66#750111181780c34a5649e3ff3bc1150c13010784_28_30) up until [the latest release of CMake](https://gitlab.kitware.com/cmake/cmake/blob/v3.15.3/Source/cmGeneratorExpressionNode.cxx#L886), the `$<CONFIG:cfg>` generator expression requires `cfg` to match the regex `^[A-Za-z0-9_]*$`. This means that escaping characters that don't match won't work, and that we need to convert configuration names.

I'll work on a fix ASAP.

**Comment by TheSlowGrowth** [comment]
Okay, that is weird. The doc clearly states that `>`, `,` and `;` can be escaped in a generator expression. Apparently `$<CONFIG:cfg>` has more strict requirements which are not documented.

I'll try to work a fix into `Jucer2Reproducer` if that's okay. This should be fairly easy to do.

**Comment by McMartin** [comment]
Currently being worked on by @TheSlowGrowth in #521.
