### ISSUE TITLE
Unknown keyword: "Use static runtime"

### ISSUE THREAD

**Issue by mhetrick** [McMartin/FRUT#533]
I accidentally bumped issue #143 when I ran into this, but it looks like FRUT does support this setting.

I'm working on porting one of our projects to a CMake build as a test, and I've run into trouble with our Visual Studio 16 2019 exporter. When calling "cmake .." from the plugin's build directory, the compiler settings are detected correctly, but I then get an error: 

```
-- Detecting CXX compile features - done
-- CMAKE_VS_WINDOWS_TARGET_PLATFORM_VERSION (10.0.18362.0) doesn't match WINDOWS_TARGET_PLATFORM (8.1).
CMake Error at C:/Users/Tricky/Desktop/FRUT Test/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:2601 (message):
  Unknown keyword: "Use static runtime"
Call Stack (most recent call first):
  C:/Users/Tricky/Desktop/FRUT Test/FRUT/prefix/FRUT/cmake/Reprojucer.cmake:1371 (_FRUT_parse_arguments)
  CMakeLists.txt:514 (jucer_export_target_configuration)
```

Inside of CMakeLists.txt, the following blocks represent the exporter:

```
jucer_export_target_configuration(
  "Visual Studio 2019"
  NAME "Debug"
  DEBUG_MODE ON
  EXTRA_LIBRARY_SEARCH_PATHS
    "..\\\\..\\\\Libraries\\\\BXLicenser\\\\Lib\\\\Win\\\\vs2019\\\\x64"
  ENABLE_PLUGIN_COPY_STEP ON
  VST_LEGACY_BINARY_LOCATION "%ProgramW6432%\\VstPlugins\\Unfiltered Audio\\"
  RUNTIME_LIBRARY "Use static runtime"
)

jucer_export_target_configuration(
  "Visual Studio 2019"
  NAME "Release"
  DEBUG_MODE OFF
  EXTRA_LIBRARY_SEARCH_PATHS
    "..\\\\..\\\\Libraries\\\\BXLicenser\\\\Lib\\\\Win\\\\vs2019\\\\x64"
  PREPROCESSOR_DEFINITIONS
    "BXPROTECTED=1"
  ENABLE_PLUGIN_COPY_STEP ON
  VST_LEGACY_BINARY_LOCATION "%ProgramW6432%\\VstPlugins\\Unfiltered Audio\\"
  RUNTIME_LIBRARY "Use static runtime"
)
```

**Comment by McMartin** [comment]
HI @mhetrick,

Thank you very much for testing FRUT! 

What you encountered is a quirk of the CMake syntax... The function `jucer_export_target_configuration` has 5 required arguments: 
https://github.com/McMartin/FRUT/blob/3052055ec4395676b9d9125b3ad77db6c8d527dc/cmake/Reprojucer.cmake#L1254-L1256
The other arguments (from `EXTRA_LIBRARY_SEARCH_PATHS` to `"Use static runtime"`) are put together in a "list" called `ARGN`. I wrote "list" between quotes, because in CMake there are actually only strings. A list in CMake is a string containing items separated by semicolons (`;`). "But what about literal semicolons then?" you might ask. Well, you would escape them using a backslash, and this is what is happening in your case. The backslash at the end of the VST binary location is escaping the semicolon that separates it from `RUNTIME_LIBRARY` when all arguments are together in `ARGN`:
```
VST_LEGACY_BINARY_LOCATION;%ProgramW6432%\VstPlugins\Unfiltered Audio\;RUNTIME_LIBRARY;Use static runtime
```
When CMake decomposes `ARGN`, we end-up with:
- `VST_LEGACY_BINARY_LOCATION`
- `%ProgramW6432%\VstPlugins\Unfiltered Audio;RUNTIME_LIBRARY`
- `Use static runtime`

The solution is to remove the trailing `\\` at the end of `%ProgramW6432%\\VstPlugins\\Unfiltered Audio\\`. You also need to change the Windows syntax for environment variable to use [CMake's `ENV` operator](https://cmake.org/cmake/help/latest/variable/ENV.html):
```cmake
  VST_LEGACY_BINARY_LOCATION "$ENV{ProgramW6432}\\VstPlugins\\Unfiltered Audio"
```

I guess we could make `Jucer2Reprojucer` sanitize paths by removing trailing backslashes to avoid getting these weird "Unknown keyword" errors (https://github.com/McMartin/FRUT/issues/534).
We should also make `Reprojucer.cmake` deal with the Windows syntax for environment variables (https://github.com/McMartin/FRUT/issues/535) so you wouldn't have to do the change manually.

I hope this helps. Don't hesitate to open new issues if you encounter other problems.

**Comment by mhetrick** [comment]
Excellent! Thank you for the fast response and clear explanation. I've used CMake a bit for other projects, but not with enough depth to understand and catch the cases like this.
