### ISSUE TITLE
Ignore warning from Juce

### ISSUE THREAD

**Issue by WGuLL** [McMartin/FRUT#559]
Hi,

I'm using FRUT on the commit 764207c.
The warnings from Juce don't seem to be ignored when I generate our projects with Juce2Reprojucer.
It causes us a lot of trouble since our warning level is more strict. 
I wasn't even aware warnings were supposed to be ignored until I saw this #9 ^^
However this issue is pretty old now.

Is there a way to ignore warnings from Juce on the current version?

**Comment by McMartin** [comment]
Hi @WGuLL,

https://github.com/McMartin/FRUT/issues/9 was resolved by https://github.com/McMartin/FRUT/pull/451, which was merged on December 16, 2018, i.e. 4 months after the commit of FRUT you are currently using.

Then in https://github.com/McMartin/FRUT/pull/493 (merged on May 7, 2019), I added support for per-file compiler flags, like in Projucer.

So there are actually 2 ways in FRUT of dealing with different warning levels between your own code and the JUCE code!

**First way: set compiler flags on the JUCE modules sources**
`Reprojucer.cmake` set a variable called `JUCER_PROJECT_MODULE_<module>_SOURCES` when you call `jucer_project_module(<module> ...`. That variable contains the list of source files to compile from that JUCE module (for instance `juce_core.cpp` or `juce_core.mm` for the `juce_core` module). You can then use these variables to set whatever compiler flags you want on the JUCE code.
Here is a concrete example:
https://github.com/McMartin/FRUT/blob/6fdfa009fce0ebcbdc81c673abd38644ff42b428/Jucer2Reprojucer/CMakeLists.txt#L240-L250
Since there is nothing equivalent to this way in Projucer, it won't work well with re-generating a `CMakeLists.txt` file from a `.jucer` file using `Jucer2Reprojucer`.

**Second way: set compiler flags on your own sources**
You can associate source files with a "compiler flag scheme" when you call `jucer_project_files`:
https://github.com/McMartin/FRUT/blob/06d8ad6bad5cac1b7e5b95541d69a1885d7d2bc2/Jucer2Reprojucer/CMakeLists.txt#L76-L80
(the compiler flag scheme is optional, but you have to repeat it for each file on which you want it to apply).
Then, in each exporter, you can define what compiler flags should be added to files for each scheme:
https://github.com/McMartin/FRUT/blob/06d8ad6bad5cac1b7e5b95541d69a1885d7d2bc2/Jucer2Reprojucer/CMakeLists.txt#L101-L104
https://github.com/McMartin/FRUT/blob/06d8ad6bad5cac1b7e5b95541d69a1885d7d2bc2/Jucer2Reprojucer/CMakeLists.txt#L135-L138
https://github.com/McMartin/FRUT/blob/06d8ad6bad5cac1b7e5b95541d69a1885d7d2bc2/Jucer2Reprojucer/CMakeLists.txt#L186-L189
Projucer supports these "compiler flag schemes" since version 5.4.2, so that way works well with re-generating a `CMakeLists.txt` file from a `.jucer` file using `Jucer2Reprojucer`.

I hope this helps!

**Comment by McMartin** [comment]
And I almost forgot, thank you very much for keeping on using FRUT! ❤️

**Comment by WGuLL** [comment]
You're welcome! :D FRUT is awesome!
I'm going to try the first solution and let you know if it works.

**Comment by WGuLL** [comment]
Hi,
I upgraded Juce and added our warnings as a custom compiler flag scheme. It works!

**Comment by McMartin** [comment]
@WGuLL I guess you reopened the issue by accident, since it was right after closing it. I'll close it now, as you seem to have a working solution.
