### ISSUE TITLE
Using different binary name does not work properly

### ISSUE THREAD

**Issue by eyalamirmusic** [McMartin/FRUT#599]
Setting in the Projucer exporter a different binary name than the default one (under Xcode->Binary name) creates and executable that can't be run, at least under OSX.

To reproduce:
Clone the demo repo:
https://github.com/eyalamirmusic/JUCECmakeRepoPrototype

Look at "DifferentBinaryName" under the "Apps" folder.
Try to build, and then manually run "SpecialName.app".

**Comment by McMartin** [comment]
@eyalamirmusic 

Thanks for reporting this bug!

There is a problem with the `Info.plist` written by `Reprojucer.cmake` when using a non-Xcode generator, such as Unix Makefiles (the default on macOS), or Ninja.

The bug is in these lines:
https://github.com/McMartin/FRUT/blob/d6d1049732184eaf1ec3d21a92d27336d9670b7c/cmake/Reprojucer.cmake#L4091-L4096
