### ISSUE TITLE
PREBUILD and POSTBUILD for Linux Makefiles

### ISSUE THREAD

**Issue by volkanozyilmaz** [McMartin/FRUT#633]
Hi Guys, 

I see I can use `PREBUILD_SHELL_SCRIPT` and `POSTBUILD_SHELL_SCRIPT` for `OSX`. 

I can also use  `PREBUILD_COMMAND` and `POSTBUILD_COMMAND` for `Windows (Visual Studio 201X)`. 

I could't find any similar command for `Linux Makefiles`. Are there any similar functionality for `Linux Makefiles`? 

Volkan

**Comment by McMartin** [comment]
Hi Volkan,

`PREBUILD_SHELL_SCRIPT`, `POSTBUILD_SHELL_SCRIPT`, `PREBUILD_COMMAND`, and `POSTBUILD_COMMAND` correspond to the equivalent Projucer settings. Since Projucer doesn't have similar settings for the "Linux Makefile" exporter, `Reprojucer.cmake` doesn't have them either.

However, you can use the CMake command [`add_custom_command`](https://cmake.org/cmake/help/latest/command/add_custom_command.html#build-events) to do something similar on Linux. Let me know if you need help with using it.

**Comment by volkanozyilmaz** [comment]
Thanks for the reply McMartin. I ended up with the .sh files for now. I thought add_custom_comand section in CMakefiles.txt but I realized that when I run FRUT again, my command section will be lost. Somehow if we can add it with FRUT would be great.
