### ISSUE TITLE
JUCE 6 Cmake support....

### ISSUE THREAD

**Issue by rorywalsh** [McMartin/FRUT#652]
Hi @McMartin, this is more a question than an issue, is FRUT JUCE version agnostic? As far as you can tell, will FRUT work just fine with JUCE6 for example, even though it has its own CMake exporter? The reason I'm asking is I dearly want to ditch the Projucer, but don't have a license for JUCE6. I'm trying to decide if I should switch now, or wait till I can get my hands on JUCE 6. 

I've use FRUT for a few different projects, it's great. But the project I have in mind is quite large, so I've been putting off migrating...

**Comment by McMartin** [comment]
Hi @rorywalsh,

FRUT tries to support JUCE from version 4.2.0 until the latest one (6.0.1 at time of writing). However, since there were a lot of changes in JUCE and Projucer over all these versions (spanning more than 4 years!), there might be bugs in FRUT, or things that FRUT doesn't do exactly like Projucer.

FRUT should work fine with JUCE 6 since I merged https://github.com/McMartin/FRUT/pull/650 and https://github.com/McMartin/FRUT/pull/624. FRUT doesn't use any of the CMake code from JUCE 6, so that doesn't make a bigger difference than between JUCE 4 and JUCE 5 for instance.

> the project I have in mind is quite large, so I've been putting off migrating...

I would be more than happy to help you convert such a project! Let me know if you are interested.

**Comment by rorywalsh** [comment]
Thanks @McMartin I think I would definitely feel more comfortable using your system than the one that JUCE supports now. Simply because you offer far better support! I'll reach out to you when I start the process of migration ;)

**Comment by rorywalsh** [comment]
Just a follow up here. I thought that once I run:

`../FRUT/prefix/FRUT/bin/Jucer2CMake reprojucer myPlugin.jucer ../FRUT/prefix/FRUT/cmake/Reprojucer.cmake`

I would no longer need to have access to the FRUT source, and everything needed to build with Cmake, and generate project files would be in my project source folder. But it seems this is not the case as I need access to Reproducer.cmake. Is there any way to create a completely standalone project folder, without having to include FRUT?

**Comment by McMartin** [comment]
What was installed under `../FRUT/prefix/FRUT` is all you need to use FRUT.

`Jucer2CMake` only writes a very simple `CMakeLists.txt` file. All the actual logic is in `Reprojucer.cmake` (which is more than 6000 lines long), and in the tools (BinaryDataBuilder, IconBuilder, PListMerger, and XcassetsBuilder) that it relies on.

**Comment by rorywalsh** [comment]
`What was installed under ../FRUT/prefix/FRUT is all you need to use FRUT.`

Perfect. ;)
