### ISSUE TITLE
install fails on macOS 10.14.6

### ISSUE THREAD

**Issue by t-scale** [McMartin/FRUT#690]
Following install guide with same folder structure.
Fails after both `cmake --build . --target install` and `cmake --build . --target install --parallel `

I've a lot of errors saying "JUCE requires C++14 or later".

I'm not sure why, as I've no issues with JUCE/Projucer and i've the latest Clang installed.
I'm on macOS Mojave (10.14.6). CMake 3.20.4. JUCE 6.

**Comment by McMartin** [comment]
@t-scale thanks a bunch for trying out FRUT and for reporting this problem!

The root cause is a somewhat recent commit in JUCE (https://github.com/juce-framework/JUCE/commit/78be43888e92dc008e8fc6c467012a1137c98a55) that makes it require C++14 (instead of C++11), and I haven't made FRUT deal with that change yet.

The short term solution is to use an older commit of JUCE, for instance https://github.com/juce-framework/JUCE/commit/0c56fa8fa0f988c4ff811eb2aabe50e646bbd09b, which is the last commit that doesn't require C++14.

I'll try to work on making FRUT handle both C++ requirements in JUCE as soon as possible, so you and other FRUT users are not blocked anymore.

**Comment by McMartin** [comment]
> i will try rolling back to that JUCE commit to give FRUT a try.

@t-scale you don't need to roll back to that JUCE commit, I've fixed the issue in FRUT itself (see https://github.com/McMartin/FRUT/pull/691). And now FRUT can build with JUCE 6.1.0 (see https://github.com/McMartin/FRUT/pull/692).
