### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by benediktadams** [McMartin/FRUT#700]
Currently building a JUCE project through FRUT ignores the ARM build target. 

On Xcode I can build my Projucer build configuration for "All Apple Devices", so it compiles a universal binary for x86_64 and arm64. 

I would expect FRUT to do the same if not otherwise specified with an `ARCH=x86_64` flag in the Custom XCode Flags field on Projucer, which is how you make XCode ignore the arm build target.

**Comment by McMartin** [comment]
@benediktsailer thanks for opening this issue! 

As discussed on Discord, one can pass `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"` to `cmake` to make Universal Binary builds. However, `Reprojucer.cmake` should reproduce what Projucer does as closely as possible, so I consider this missing ARM support in FRUT a bug. I'll have a look at fixing it as soon as possible.

**Comment by Xav83** [comment]
Hi @McMartin 🙂

I'm also experiencing a problem with the architectures `x86_64` and `arm64` on OSX.

Here is a little bit of context to explain the problem:
I am currently trying to upgrade the version of Xcode that we are using to the latest version (13.1), and I have issues with the plugin targets.
Actually, we are also using JUCE and FRUT to generates some static libraries, and everything works fine with the new Xcode, so it seems to comes from the plugins targets.

So the problem is that we only want to build for `x86_64` (as we are only going to integrate arm support later), but the targets generated in Xcode, for our plugins, are for universal binaries (`arm64` and `x86_64`) in Debug and Release configurations (cf the screenshot), which trigger some errors when trying to link to our static libraries which are set up only for the `x86_64` architecture.
<img width="789" alt="Screenshot 2021-11-29 at 15 15 25" src="https://user-images.githubusercontent.com/6787157/143883748-79d69343-ddb1-4ce3-a420-71df2cb61235.png">

In order to solve this problem, I have tried several things without success:
- I used the Projucer to specify the architecture to use (x86_64 only), which added the attribut `xcodeValidArchs="x86_64"` to the jucer of the project.
- I specified the value for the cmake variable `CMAKE_OSX_ARCHITECTURES` in the CMakeLists.txt file of the project.
- I also tried to specify the value for the cmake variable `CMAKE_OSX_ARCHITECTURES` in the command line generating the project: `cmake .. -G Xcode -DCMAKE_OSX_ARCHITECTURES="x86_64"`
- I finally tried to modify the value of the architecture for a specific configuration on a target of the project in the cmake script: `set_target_properties(<pluginName>_Shared_Code PROPERTIES OSX_ARCHITECTURES x86_64)` and `set_target_properties(<pluginName>_Shared_Code PROPERTIES OSX_ARCHITECTURES_Debug x86_64)`.

Whatever the solution I tried, I still have the same issue:
```
ld: symbol(s) not found for architecture arm64
```
And some warnings telling me that the static libraries we have are only generated for `x86_64` architecture, and not the `arm64` architecture.

Here are all the information I have for now.
I hope it will help you to have an idea about what the problem is and how to solve it. 😊

PS: Thank you for you amazing work on FRUT ! I simplifies ours so much ! 👍 

Additional informations:
OSX version: 11.6
Xcode version: 13.1
JUCE version: 6.1.2
FRUt version: e3cf94bcf4afa9e2cab3634793b0c13f51347d9b (currently the last commit on the `main` branch)

**Comment by Xav83** [comment]
PPS: I don't know if this information is of some importance to you @McMartin , but, when using the generator `Unix Makefiles`, on OSX, we don't have any warning from the linker and everything is generating without error

**Comment by Xav83** [comment]
PPPS: Specifying the right value of the architecture (`x86_64`) to each configuration via the Xcode GUI, makes the build succeed ! So it seems that this is a "generation of the Xcode project" issue.

**Comment by McMartin** [comment]
Hi @Xav83,

Thanks a lot for the very detailed report, as usual! 

> * I used the Projucer to specify the architecture to use (x86_64 only), which added the attribut `xcodeValidArchs="x86_64"` to the jucer of the project.

This cannot work currently because `Jucer2CMake` and `Reprojucer.cmake` don't know about that setting (you won't find `xcodeValidArchs` in `Jucer2CMake/src/reprojucer.hpp`, nor `VALID_ARCHITECTURES` in `cmake/Reprojucer.cmake`).

I started a branch about a month ago to add that missing feature, but I don't think it's in a good enough state to be made public yet.

> * I specified the value for the cmake variable `CMAKE_OSX_ARCHITECTURES` in the CMakeLists.txt file of the project.
> * I also tried to specify the value for the cmake variable `CMAKE_OSX_ARCHITECTURES` in the command line generating the project: `cmake .. -G Xcode -DCMAKE_OSX_ARCHITECTURES="x86_64"`
> * I finally tried to modify the value of the architecture for a specific configuration on a target of the project in the cmake script: `set_target_properties(<pluginName>_Shared_Code PROPERTIES OSX_ARCHITECTURES x86_64)` and `set_target_properties(<pluginName>_Shared_Code PROPERTIES OSX_ARCHITECTURES_Debug x86_64)`.

This also won't work because `Reprojucer.cmake` sets the target property `XCODE_ATTRIBUTE_ARCHS` when using the Xcode generator, which takes precedence over `OSX_ARCHITECTURES_*`.

However, `Reprojucer.cmake` only sets `XCODE_ATTRIBUTE_ARCHS` in two cases:
- on the AUv3 target (called `<plugin_name>_AUv3_AppExtension`)
- when `OSX_ARCHITECTURE` is passed to `jucer_export_target_configuration`, which in turns comes from having the `osxArchitecture` attribute on `CONFIGURATION` elements in the `.jucer` file

Could you please let me know whether you have `osxArchitecture` attributes in the `.jucer` file and what their values are? 
Could you please also try removing these `osxArchitecture` attributes and seeing whether that fixes your immediate issue? If it doesn't work, I guess I'll polish up my branch so you can give it a try.

**Comment by Xav83** [comment]
@McMartin, thanks a lot for your quick answer! 🙂

The attributes `osxArchitecture` were indeed present in the jucer of our file.
Moreover, as you suggested, removing them corrected the issue on our project ! 😃

FYI, the attributes were specified like so, in our jucer file: `osxArchitecture="64BitIntel"`

**Comment by McMartin** [comment]
@Xav83 awesome! This means I have a bit more time to polish my branch. I'll ping you here once it is ready, so you can test it and make sure that it doesn't break what is now working for you :smile:
